<a href="https://colab.research.google.com/github/yigagilbert/a-disease-predictions-model-/blob/main/disease_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import  Dense
from tensorflow.python.keras.wrappers.scikit_learn import KerasRegressor


In [2]:
from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [51]:
train = pd.read_csv('/content/gdrive/MyDrive/disease_dataset/Training.csv')
test = pd.read_csv('/content/gdrive/MyDrive/disease_dataset/Testing.csv')
train.head

<bound method NDFrame.head of       itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0  

In [52]:
l1=['back_pain','constipation','abdominal_pain','diarrhoea','mild_fever','yellow_urine',
    'yellowing_of_eyes','acute_liver_failure','fluid_overload','swelling_of_stomach',
    'swelled_lymph_nodes','malaise','blurred_and_distorted_vision','phlegm','throat_irritation',
    'redness_of_eyes','sinus_pressure','runny_nose','congestion','chest_pain','weakness_in_limbs',
    'fast_heart_rate','pain_during_bowel_movements','pain_in_anal_region','bloody_stool',
    'irritation_in_anus','neck_pain','dizziness','cramps','bruising','obesity','swollen_legs',
    'swollen_blood_vessels','puffy_face_and_eyes','enlarged_thyroid','brittle_nails',
    'swollen_extremeties','excessive_hunger','extra_marital_contacts','drying_and_tingling_lips',
    'slurred_speech','knee_pain','hip_joint_pain','muscle_weakness','stiff_neck','swelling_joints',
    'movement_stiffness','spinning_movements','loss_of_balance','unsteadiness',
    'weakness_of_one_body_side','loss_of_smell','bladder_discomfort','foul_smell_of urine',
    'continuous_feel_of_urine','passage_of_gases','internal_itching','toxic_look_(typhos)',
    'depression','irritability','muscle_pain','altered_sensorium','red_spots_over_body','belly_pain',
    'abnormal_menstruation','dischromic _patches','watering_from_eyes','increased_appetite','polyuria','family_history','mucoid_sputum',
    'rusty_sputum','lack_of_concentration','visual_disturbances','receiving_blood_transfusion',
    'receiving_unsterile_injections','coma','stomach_bleeding','distention_of_abdomen',
    'history_of_alcohol_consumption','fluid_overload','blood_in_sputum','prominent_veins_on_calf',
    'palpitations','painful_walking','pus_filled_pimples','blackheads','scurring','skin_peeling',
    'silver_like_dusting','small_dents_in_nails','inflammatory_nails','blister','red_sore_around_nose',
    'yellow_crust_ooze']



In [53]:
#List of Diseases is listed in list disease.

disease=['Fungal infection','Allergy','GERD','Chronic cholestasis','Drug Reaction',
    'Peptic ulcer diseae','AIDS','Diabetes','Gastroenteritis','Bronchial Asthma','Hypertension',
    ' Migraine','Cervical spondylosis',
    'Paralysis (brain hemorrhage)','Jaundice','Malaria','Chicken pox','Dengue','Typhoid','hepatitis A',
    'Hepatitis B','Hepatitis C','Hepatitis D','Hepatitis E','Alcoholic hepatitis','Tuberculosis',
    'Common Cold','Pneumonia','Dimorphic hemmorhoids(piles)',
    'Heartattack','Varicoseveins','Hypothyroidism','Hyperthyroidism','Hypoglycemia','Osteoarthristis',
    'Arthritis','(vertigo) Paroymsal  Positional Vertigo','Acne','Urinary tract infection','Psoriasis',
    'Impetigo']

l2=[]
for i in range(0,len(l1)):
    l2.append(0)
print(l2)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [54]:
dataframe=pd.read_csv('/content/gdrive/MyDrive/disease_dataset/Training.csv')
dataset=dataframe.values
print(dataset)

[[1 1 1 ... 0 'Fungal infection' nan]
 [0 1 1 ... 0 'Fungal infection' nan]
 [1 0 1 ... 0 'Fungal infection' nan]
 ...
 [0 0 0 ... 0 'Urinary tract infection' nan]
 [0 1 0 ... 0 'Psoriasis' nan]
 [0 1 0 ... 1 'Impetigo' nan]]


In [56]:
#Replace the values in the imported file by pandas by the inbuilt function replace in pandas.

dataframe.replace({'prognosis':{'Fungal infection':0,'Allergy':1,'GERD':2,'Chronic cholestasis':3,'Drug Reaction':4,
    'Peptic ulcer diseae':5,'AIDS':6,'Diabetes ':7,'Gastroenteritis':8,'Bronchial Asthma':9,'Hypertension ':10,
    'Migraine':11,'Cervical spondylosis':12,
    'Paralysis (brain hemorrhage)':13,'Jaundice':14,'Malaria':15,'Chicken pox':16,'Dengue':17,'Typhoid':18,'hepatitis A':19,
    'Hepatitis B':20,'Hepatitis C':21,'Hepatitis D':22,'Hepatitis E':23,'Alcoholic hepatitis':24,'Tuberculosis':25,
    'Common Cold':26,'Pneumonia':27,'Dimorphic hemmorhoids(piles)':28,'Heart attack':29,'Varicose veins':30,'Hypothyroidism':31,
    'Hyperthyroidism':32,'Hypoglycemia':33,'Osteoarthristis':34,'Arthritis':35,
    '(vertigo) Paroymsal  Positional Vertigo':36,'Acne':37,'Urinary tract infection':38,'Psoriasis':39,
    'Impetigo':40}},inplace=True)

#printing the top 5 rows of the training dataset
dataframe.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  scurring  \
0       0           0             0        0                 0  ...         0   
1       0           0             0        0                 0  ...         0   
2       0           0             0        0                 0  ...         0   
3       0           0             0        0                 0  ...         0   
4       0           0             0        0                 0  ...         0   

   skin_peeling  silver_like_dusting  small_dents_in_nails  \
0             0                    0                     0   
1             0                    0                     0   
2             0                    0                     0   
3             0                    0                     0   
4             0                    0                     0   

   inflammatory_nails  blister  red_sore_around_nose  yellow_crust_ooze  \
0                   0        0                     0                  0   
1                   0        0                     0                  0   
2                   0        0                     0                  0   
3                   0        0                     0                  0   
4                   0        0                     0                  0   

   prognosis  Unnamed: 133  
0          0           NaN  
1          0           NaN  
2          0           NaN  
3          0           NaN  
4          0           NaN  

[5 rows x 134 columns]

In [ ]:
dataframe = dataframe.drop('Unnamed: 133',axis=1)
print(dataframe)

In [95]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 133 entries, itching to prognosis
dtypes: int64(133)
memory usage: 5.0 MB


In [98]:
dataframe.describe()

itching    skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count  4920.000000  4920.000000           4920.000000          4920.000000   
mean      0.137805     0.159756              0.021951             0.045122   
std       0.344730     0.366417              0.146539             0.207593   
min       0.000000     0.000000              0.000000             0.000000   
25%       0.000000     0.000000              0.000000             0.000000   
50%       0.000000     0.000000              0.000000             0.000000   
75%       0.000000     0.000000              0.000000             0.000000   
max       1.000000     1.000000              1.000000             1.000000   

         shivering       chills   joint_pain  stomach_pain      acidity  \
count  4920.000000  4920.000000  4920.000000   4920.000000  4920.000000   
mean      0.021951     0.162195     0.139024      0.045122     0.045122   
std       0.146539     0.368667     0.346007      0.207593     0.207593   
min       0.000000     0.000000     0.000000      0.000000     0.000000   
25%       0.000000     0.000000     0.000000      0.000000     0.000000   
50%       0.000000     0.000000     0.000000      0.000000     0.000000   
75%       0.000000     0.000000     0.000000      0.000000     0.000000   
max       1.000000     1.000000     1.000000      1.000000     1.000000   

       ulcers_on_tongue  ...   blackheads     scurring  skin_peeling  \
count       4920.000000  ...  4920.000000  4920.000000   4920.000000   
mean           0.021951  ...     0.021951     0.021951      0.023171   
std            0.146539  ...     0.146539     0.146539      0.150461   
min            0.000000  ...     0.000000     0.000000      0.000000   
25%            0.000000  ...     0.000000     0.000000      0.000000   
50%            0.000000  ...     0.000000     0.000000      0.000000   
75%            0.000000  ...     0.000000     0.000000      0.000000   
max            1.000000  ...     1.000000     1.000000      1.000000   

       silver_like_dusting  small_dents_in_nails  inflammatory_nails  \
count          4920.000000           4920.000000         4920.000000   
mean              0.023171              0.023171            0.023171   
std               0.150461              0.150461            0.150461   
min               0.000000              0.000000            0.000000   
25%               0.000000              0.000000            0.000000   
50%               0.000000              0.000000            0.000000   
75%               0.000000              0.000000            0.000000   
max               1.000000              1.000000            1.000000   

           blister  red_sore_around_nose  yellow_crust_ooze    prognosis  
count  4920.000000           4920.000000        4920.000000  4920.000000  
mean      0.023171              0.023171           0.023171    20.000000  
std       0.150461              0.150461           0.150461    11.833362  
min       0.000000              0.000000           0.000000     0.000000  
25%       0.000000              0.000000           0.000000    10.000000  
50%       0.000000              0.000000           0.000000    20.000000  
75%       0.000000              0.000000           0.000000    30.000000  
max       1.000000              1.000000           1.000000    40.000000  

[8 rows x 133 columns]

In [58]:
print(dataframe)

      itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0         

In [59]:
dataset=dataframe.values
print(dataset)

[[ 1  1  1 ...  0  0  0]
 [ 0  1  1 ...  0  0  0]
 [ 1  0  1 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0 38]
 [ 0  1  0 ...  0  0 39]
 [ 0  1  0 ...  1  1 40]]


In [60]:
#Reading the  testing.csv file
tr=pd.read_csv("/content/gdrive/MyDrive/disease_dataset/Testing.csv")

#Using inbuilt function replace in pandas for replacing the values
tr.replace({'prognosis':{'Fungal infection':0,'Allergy':1,'GERD':2,'Chronic cholestasis':3,'Drug Reaction':4,
    'Peptic ulcer diseae':5,'AIDS':6,'Diabetes ':7,'Gastroenteritis':8,'Bronchial Asthma':9,'Hypertension ':10,
    'Migraine':11,'Cervical spondylosis':12,
    'Paralysis (brain hemorrhage)':13,'Jaundice':14,'Malaria':15,'Chicken pox':16,'Dengue':17,'Typhoid':18,'hepatitis A':19,
    'Hepatitis B':20,'Hepatitis C':21,'Hepatitis D':22,'Hepatitis E':23,'Alcoholic hepatitis':24,'Tuberculosis':25,
    'Common Cold':26,'Pneumonia':27,'Dimorphic hemmorhoids(piles)':28,'Heart attack':29,'Varicose veins':30,'Hypothyroidism':31,
    'Hyperthyroidism':32,'Hypoglycemia':33,'Osteoarthristis':34,'Arthritis':35,
    '(vertigo) Paroymsal  Positional Vertigo':36,'Acne':37,'Urinary tract infection':38,'Psoriasis':39,
    'Impetigo':40}},inplace=True)


In [76]:
dataset.shape

(4920, 133)

In [109]:
x=dataset[:,0:len(l1)]
print(x.shape)
y=dataset[:,-1]
y=np.reshape(y, (-1,1))
print(y.shape)

# need to scale,bt before it need to it can do in flutter
# scaler_x = MinMaxScaler()
# scaler_y = MinMaxScaler()
# print(scaler_x.fit(x))
# xscale=scaler_x.transform(x)
# print(scaler_y.fit(y))
# yscale=scaler_y.transform(y)


(4920, 95)
(4920, 1)


In [110]:
x_train,x_test,y_train,y_test=train_test_split(x,y)
# 75% 25%
# print(y_test.shape)

In [111]:
model=Sequential()
model.add(Dense(12,input_dim=len(l1),activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='linear'))
model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_24 (Dense)             (None, 12)                1152      
_________________________________________________________________
dense_25 (Dense)             (None, 8)                 104       
_________________________________________________________________
dense_26 (Dense)             (None, 1)                 9         
Total params: 1,265
Trainable params: 1,265
Non-trainable params: 0
_________________________________________________________________


In [112]:
model.compile(loss='mse',optimizer='adam',metrics=['mse','mae'])

In [113]:
history= model.fit(x_train,y_train,epochs=300,batch_size=20)

Epoch 1/300
185/185 [==============================] - 1s 2ms/step - loss: 523.6665 - mse: 523.6665 - mae: 19.5959
Epoch 2/300
185/185 [==============================] - 0s 2ms/step - loss: 339.1543 - mse: 339.1543 - mae: 14.3409
Epoch 3/300
185/185 [==============================] - 0s 2ms/step - loss: 170.0847 - mse: 170.0847 - mae: 9.3630
Epoch 4/300
185/185 [==============================] - 0s 2ms/step - loss: 102.7257 - mse: 102.7257 - mae: 7.0645
Epoch 5/300
185/185 [==============================] - 0s 2ms/step - loss: 52.9284 - mse: 52.9284 - mae: 4.5634
Epoch 6/300
185/185 [==============================] - 0s 2ms/step - loss: 30.9723 - mse: 30.9723 - mae: 3.4033
Epoch 7/300
185/185 [==============================] - 0s 2ms/step - loss: 20.8222 - mse: 20.8222 - mae: 2.7878
Epoch 8/300
185/185 [==============================] - 0s 2ms/step - loss: 15.3968 - mse: 15.3968 - mae: 2.3838
Epoch 9/300
185/185 [==============================] - 0s 2ms/step - loss: 12.4987 - mse: 12.4

In [114]:
def scatterplt(disea):
    x = ((dataframe.loc[disea]).sum())#total sum of symptom reported for given disease
    x.drop(x[x==0].index,inplace=True)#droping symptoms with values 0
    print(x.values)
    y = x.keys()#storing nameof symptoms in y
    print(len(x))
    print(len(y))
    plt.title(disea)
    plt.scatter(y,x.values)
    plt.show()

In [115]:
def scatterinp(sym1,sym2,sym3,sym4,sym5):
    x = [sym1,sym2,sym3,sym4,sym5]#storing input symptoms in y
    y = [0,0,0,0,0]#creating and giving values to the input symptoms
    if(sym1!='Select Here'):
        y[0]=1
    if(sym2!='Select Here'):
        y[1]=1
    if(sym3!='Select Here'):
        y[2]=1
    if(sym4!='Select Here'):
        y[3]=1
    if(sym5!='Select Here'):
        y[4]=1
    print(x)
    print(y)
    plt.scatter(x,y)
    plt.show()

In [ ]:
# def model_test():
#     if((Symptom1.get()=="Select Here") or (Symptom2.get()=="Select Here")):
#             # pred1.set(" ")
#             print("System","Kindly Fill atleast first two Symptoms")
            
#     else:
#             from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
#             y_pred=model.predict(x_test)
#             print("Decision Tree")
#             print("Accuracy")
#             print(accuracy_score(y_test, y_pred))
#             print(accuracy_score(y_test, y_pred,normalize=False))
#             print("Confusion matrix")
#             conf_matrix=confusion_matrix(y_test,y_pred)
#             print(conf_matrix)
#             psymptoms = [Symptom1.get(),Symptom2.get(),Symptom3.get(),Symptom4.get(),Symptom5.get()]

#             for k in range(0,len(l1)):
#                 for z in psymptoms:
#                     if(z==l1[k]):
#                         l2[k]=1

#             inputtest = [l2]
#             predict = model.predict(inputtest)
#             predicted=predict[0]

In [122]:
psymptoms = ['diarrhoea','congestion','yellow_urine','vomiting','drying_and_tingling_lips']#'nausea']

for k in range(0,len(l1)):
    for z in psymptoms:
        if(z==l1[k]):
             l2[k]=1
inputtest = [l2]
predict = model.predict(inputtest)
predicted=predict[0]
print(l2)
print(predicted)
# print(disease[predicted])

# scatterplt(disease[predicted])

[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[6.5654936]


In [123]:
psymptoms = ['diarrhoea','headache','chills','prominent_veins_on_calf','nausea']

for k in range(0,len(l1)):
    for z in psymptoms:
        if(z==l1[k]):
             l2[k]=1
# xnew=np.array([l2])
xnew=[l2]
ynew= model.predict(xnew)
print("X=%s, Predicted=%s" % (xnew[0], ynew[0]))

X=[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], Predicted=[17.224129]


In [ ]:
model.save('/content/gdrive/MyDrive/disease_dataset/predtest.h5')

In [ ]:
from tensorflow.python import keras
import tensorflow

modelnew = keras.models.load_model('/content/gdrive/MyDrive/disease_dataset/predtest.h5')
converter=tensorflow.lite.TFLiteConverter.from_keras_model(modelnew)
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)

INFO:tensorflow:Assets written to: /tmp/tmp6gv5qx9i/assets


2312

In [ ]:
# xnew=np.array([[913,1072,1595,3736,5340]])
psymptoms = ['diarrhoea','headache','chills','prominent_veins_on_calf','nausea']

for k in range(0,len(l1)):
    for z in psymptoms:
        if(z==l1[k]):
             l2[k]=1
# xnew=np.array([l2])
xnew=[l2]
ynew= modelnew.predict(xnew)
print("X=%s, Predicted=%s" % (xnew[0], ynew[0]))

X=[ 913 1072 1595 3736 5340], Predicted=[3213.0403]


In [ ]:
# print(history.history.keys())
# # "Loss"
# plt.plot(history.history['loss'])
# plt.plot(history.history['mse'])
# plt.title('model loss')
# plt.ylabel('loss')
# plt.xlabel('epoch')
# plt.legend(['train', 'validation'], loc='upper left')
# plt.show()